CREATE TABLE USER
(
    ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
    ACCOUNT_ID VARCHAR(128),
    NICKNAME VARCHAR(128),
    TOKEN VARCHAR(50),
    CREATE_TIME BIGINT,
    MODIFIED_TIME BIGINT
)